---
- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Enable new unattended-upgrades settings
  ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: true
