---
- name: Create dedicated Wheelodex user
  ansible.builtin.user:
    name: "{{ wheelodex_user }}"
    home: /home/{{ wheelodex_user }}
    create_home: true
    shell: /bin/bash

- name: Check if pip is installed for user
  ansible.builtin.stat:
    path: /home/{{ wheelodex_user }}/.local/bin/pip3
  register: pipstat

- name: Install pip
  when: not pipstat.stat.exists or upgrade_pip
  block:
    - name: Download get-pip.py
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
        mode: "0644"
        force: true
      changed_when: true

    - name: Run get-pip.py
      ansible.builtin.command: python3 /tmp/get-pip.py --user --upgrade
      args:
        creates: /home/{{ wheelodex_user }}/.local/bin/pip3
      become: true
      become_user: "{{ wheelodex_user }}"

- name: Install virtualenv for user
  ansible.builtin.pip:
    name: virtualenv
    extra_args: --user
    executable: ~/.local/bin/pip3
    state: "{{ wheelodex_upgrade_pip | ternary('latest', 'present') }}"
  become: true
  become_user: "{{ wheelodex_user }}"

- name: Create WSGI file
  ansible.builtin.copy:
    src: wsgi.py
    dest: "{{ wheelodex_wsgi_file }}"
    owner: "{{ wheelodex_user }}"
    mode: "0644"
  notify:
    - Restart uWSGI

- name: Create config file
  ansible.builtin.template:
    src: config.py
    dest: "{{ wheelodex_config_file }}"
    owner: "{{ wheelodex_user }}"
    mode: "0644"
  notify:
    - Restart uWSGI

- name: Create wheelodex wrapper script
  ansible.builtin.template:
    src: wheelodex.sh
    dest: /usr/local/bin/wheelodex
    mode: "0755"
    owner: "{{ wheelodex_user }}"

- name: Create log directory
  ansible.builtin.file:
    path: "{{ wheelodex_log_path }}"
    state: directory
    owner: "{{ wheelodex_user }}"
    mode: "0755"

- name: Configure log rotation
  ansible.builtin.template:
    src: logrotate
    dest: /etc/logrotate.d/wheelodex
    # The logrotate manpage doesn't mention that you need to chown root, but
    # it's very necessary.
    owner: root
    group: root
    mode: "0644"

- name: Install new version of Wheelodex
  ansible.builtin.import_tasks: new_code.yml
  when: wheelodex_wheel is defined

- name: Install systemd failure notification script
  ansible.builtin.template:
    src: mail-systemd-failure.sh
    dest: /usr/local/bin/mail-systemd-failure
    mode: "0755"

- name: Configure systemd jobs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  with_items:
    - mail-systemd-failure@.service
    - process-wheels.service
    - process-wheels.timer
    - register-wheels.service
    - register-wheels.timer
  notify:
    - Reload systemd

- name: Enable process-wheels timer
  ansible.builtin.systemd:
    name: process-wheels.timer
    enabled: true

- name: Enable register-wheels timer
  ansible.builtin.systemd:
    name: register-wheels.timer
    enabled: true

- name: Start process-wheels timer
  ansible.builtin.systemd:
    name: process-wheels.timer
    state: started

- name: Start register-wheels timer
  ansible.builtin.systemd:
    name: register-wheels.timer
    state: started
