---
- name: Create dedicated Wheelodex user
  ansible.builtin.user:
    name: "{{ wheelodex_user }}"
    groups: systemd-journal
    home: /home/{{ wheelodex_user }}
    create_home: true
    shell: /bin/bash

- name: Install pip and virtualenv
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-virtualenv
    state: present

- name: Create WSGI file
  ansible.builtin.copy:
    src: wsgi.py
    dest: "{{ wheelodex_wsgi_file }}"
    owner: "{{ wheelodex_user }}"
    mode: "0644"
  notify:
    - Restart uWSGI

- name: Create config file
  ansible.builtin.template:
    src: config.py.j2
    dest: "{{ wheelodex_config_file }}"
    owner: "{{ wheelodex_user }}"
    mode: "0644"
  notify:
    - Restart uWSGI

- name: Create wheelodex wrapper script
  ansible.builtin.template:
    src: wheelodex.sh
    dest: /usr/local/bin/wheelodex
    mode: "0755"
    owner: "{{ wheelodex_user }}"

- name: Create log directory
  ansible.builtin.file:
    path: "{{ wheelodex_log_path }}"
    state: directory
    owner: "{{ wheelodex_user }}"
    mode: "0755"

- name: Configure log rotation
  ansible.builtin.template:
    src: logrotate
    dest: /etc/logrotate.d/wheelodex
    # The logrotate manpage doesn't mention that you need to chown root, but
    # it's very necessary.
    owner: root
    group: root
    mode: "0644"

- name: Install new version of Wheelodex
  ansible.builtin.import_tasks: new_code.yml
  when: wheelodex_wheel is defined

- name: Install wheelodex-runner script
  ansible.builtin.copy:
    src: wheelodex-runner.py
    dest: /usr/local/bin/wheelodex-runner
    owner: root
    mode: "0755"

- name: Install systemd failure notification script
  ansible.builtin.template:
    src: mail-systemd-failure.sh
    dest: /usr/local/bin/mail-systemd-failure
    owner: root
    mode: "0755"

- name: Let wheelodex user sudo to start wheelodex jobs
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/wheelodex
    line: '{{ wheelodex_user }} ALL= NOPASSWD: /bin/systemctl start {{ item }}'
    validate: 'visudo -cf %s'
    mode: "0440"
    owner: root
    group: root
    create: true
    backup: true
  with_items:
    - wheelodex-process-orphan-wheels.service
    - wheelodex-process-queue.service
    - wheelodex-purge-old-versions.service
    - wheelodex-scan-changelog.service

- name: Remove old systemd jobs
  ansible.builtin.file:
    path: /etc/systemd/system/{{ item }}
    state: absent
  with_items:
    - process-wheels.service
    - process-wheels.timer
    - register-wheels.service
    - register-wheels.timer
  notify:
    - Reload systemd

- name: Configure systemd jobs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: "0644"
  with_items:
    - wheelodex-process-orphan-wheels.service
    - wheelodex-process-queue.service
    - wheelodex-purge-old-versions.service
    - wheelodex-runner.service
    - wheelodex-runner.timer
    - wheelodex-scan-changelog.service
  notify:
    - Reload systemd

- name: Enable & start wheelodex-runner timer
  ansible.builtin.systemd:
    name: wheelodex-runner.timer
    enabled: true
    state: started

- name: Ensure wheelodex services aren't restarted on package upgrades
  ansible.builtin.copy:
    dest: /etc/needrestart/conf.d/wheelodex.conf
    content:
      # Prevent wheelodex services from being restarted on package upgrades
      # <https://discourse.ubuntu.com/t/44671>
      $nrconf{override_rc}{qr(^wheelodex-.*\.service$)} = 0;
    mode: "0644"
