---
- name: Install uWSGI
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present
    update_cache: false

- name: Configure uWSGI
  ansible.builtin.template:
    src: wheelodex.ini
    dest: /etc/uwsgi/apps-available/wheelodex.ini
    mode: "0644"
  notify:
    - Restart uWSGI

- name: Enable uWSGI app configuration
  ansible.builtin.file:
    src: /etc/uwsgi/apps-available/wheelodex.ini
    path: /etc/uwsgi/apps-enabled/wheelodex.ini
    state: link
  notify:
    - Restart uWSGI
