---
- assert: that='server_names is defined and (server_names|length > 0)'

- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true
    state: present

- name: Link certbot executable
  file:
    src: /snap/bin/certbot
    path: /usr/bin/certbot
    state: link

- name: Get SSL certificates
  ### TODO: Ensure this does nothing when server_names is unchanged
  command: |
    certbot run
        --nginx
        --rsa-key-size 4096
        --expand
        --cert-name {{certname|quote}}
        --email {{certbot_email|quote}}
        --domains {{server_names|join(',')|quote}}
        --non-interactive
        --agree-tos
  #args:
  #  creates: /etc/letsencrypt

# Cert autorenewal is done by a cronjob installed by the certbot package
