"""Add EntryPointGroup.summary

Revision ID: 2508919c9f86
Revises:
Create Date: 2018-10-08 22:38:52.231851+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2508919c9f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'entry_point_groups',
        sa.Column('summary', sa.Unicode(length=2048), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_point_groups', 'summary')
    # ### end Alembic commands ###
