"""Index WheelData.processed

Revision ID: b37f849a527d
Revises: 945b037bada0
Create Date: 2020-03-29 18:22:28.520949+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f849a527d'
down_revision = '945b037bada0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('wheel_data_processed_idx', 'wheel_data', [sa.text('processed DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('wheel_data_processed_idx', table_name='wheel_data')
    # ### end Alembic commands ###
