"""
Make wheel digests non-nullable

Revision ID: ce07a6a94af5
Revises: a9bd6c2d6b32
Create Date: 2025-11-21 21:37:03.575086+00:00
"""

from __future__ import annotations
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic:
revision: str = "ce07a6a94af5"
down_revision: str | None = "a9bd6c2d6b32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wheels", schema=None) as batch_op:
        batch_op.alter_column(
            "md5", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "sha256", existing_type=sa.VARCHAR(length=64), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wheels", schema=None) as batch_op:
        batch_op.alter_column(
            "sha256", existing_type=sa.VARCHAR(length=64), nullable=True
        )
        batch_op.alter_column("md5", existing_type=sa.VARCHAR(length=32), nullable=True)

    # ### end Alembic commands ###
